In [1]:
# moved from the end of dataset_preprocessing.ipynb

In [ ]:
def getOutput(uniqueTxtInCellYouWantToRetrieve='', finalExecCell=True):
    '''
    Prerequisites:
    pip/conda intstall scrapbook
    Save the .ipynb file first before using this function
    '''
    nb = sb.read_notebook(nbName if nbName != '' else os.path.basename(globals()['__vsc_ipynb_file__']))
    mx = -1
    chosenCell = -1
    i = 0
    for cell in nb.cells:
        if (uniqueTxtInCellYouWantToRetrieve in cell['source']):
            break
        if ('execution_count' in cell and cell['execution_count'] > mx):
            mx = cell['execution_count']
            chosenCell = i
        i += 1
        
    s = ''
    for txt in cell[i]['outputs']:
        s += txt['text']
    return s

In [ ]:
fig = px.line(pd.DataFrame(
        {'Train Score':list(history['acc'])+[0.8,0.9], 'Val Score':list(history['val_acc'])+[0.8,0.9]}, 
        index=pd.RangeIndex(start=1, stop=len(list(history['acc']))+3, name='Epoch') # +1
    ), 
    markers=True, width=1380)
fig.update_layout(yaxis_title="Accuracy", legend_title_text="Accuracy")
fig.add_annotation(
    text=f" Test Score: <br>{history['test_acc']}",
    align="center",
    showarrow=False,
    xref="paper",
    yref="paper",
    font=dict(color="black", size=13),
    y=0.75,
    x=1.03,
    bordercolor='black',
    borderwidth=2,
    xanchor="left",
)

In [ ]:
fig = px.line(pd.DataFrame(
        {'Train Score':history['f1_score']+[0.8,0.9], 'Val Score':history['val_f1_score']+[0.8,0.9]}, 
        index=pd.RangeIndex(start=1, stop=len(history['f1_score'])+3, name='epoch') # +1
    ), 
    markers=True)
fig.update_layout(yaxis_title="F1 Score")

The following blocks of code are used when the number of epochs is greater than 1

In [ ]:
d = history['f1_score'].copy()
# np.vstack((d, np.array([1,2,3,4,5,6,7,8]))).shape
# f = np.asmatrix(d)
d

array([0.8262 , 0.91264, 0.54549, 0.80033, 0.27231, 0.34677, 0.7385 ,
       0.59454], dtype=float32)

In [ ]:
dfTmp = pd.DataFrame(history['f1_score'], columns=['a'])
dfTmp.index += 1
dfTmp

a
1  0.82620
2  0.91264
3  0.54549
4  0.80033
5  0.27231
6  0.34677
7  0.73850
8  0.59454

In [ ]:
classNameToNum = pklLoad('dataset_related/imgTypeToNum.pickle')
classList = list(classNameToNum.keys())
dfTmp = pd.DataFrame(history['f1_score'], columns=classList)
dfTmp.index += 1
fig = px.line(dfTmp, title="Training F1 Scores", markers=True, width=1200)
fig.update_layout(xaxis=dict(title="Epochs"), yaxis=dict(title="F1 Score"), legend_title_text="Class Type")
fig.show()

ValueError: Shape of passed values is (8, 1), indices imply (8, 8)

In [ ]:
# htest.history['f1_score']
tsst = np.round(np.array(htest.history['f1_score']) + 1, 2)
tsst

array([[1.37, 1.43, 1.29, 1.  , 1.  , 1.  , 1.12, 1.39],
       [1.43, 1.  , 1.  , 1.  , 1.  , 1.  , 1.32, 1.  ],
       [1.57, 1.51, 1.  , 1.  , 1.07, 1.  , 1.12, 1.  ],
       [1.65, 1.56, 1.13, 1.  , 1.  , 1.  , 1.17, 1.  ],
       [1.56, 1.72, 1.18, 1.  , 1.  , 1.  , 1.2 , 1.  ]], dtype=float32)

In [ ]:
dfTmp

1     2     3     4     5
00. selfies           1.37  1.43  1.57  1.65  1.56
10. fmemes            1.43  1.00  1.51  1.56  1.72
20. ememes            1.29  1.00  1.00  1.13  1.18
30. eSocialMedia      1.00  1.00  1.00  1.00  1.00
40. fFbPosts          1.00  1.00  1.07  1.00  1.00
50. fTwtrPosts        1.00  1.00  1.00  1.00  1.00
60. fTxtMssgs         1.12  1.32  1.12  1.17  1.20
70. eGreetingAndMisc  1.39  1.00  1.00  1.00  1.00

['solid', 'dot', 'dash', 'longdash', 'dashdot', 'longdashdot']

In [ ]:
dashStyles = ['solid', 'dot', 'dash', 'longdash', 'dashdot', 'longdashdot']
classNameToNum = pklLoad('dataset_related/imgTypeToNum.pickle')
classList = list(classNameToNum.keys())
dfTmp = pd.DataFrame(tsst, columns=classList) # history['val_f1_score']
dfTmp.index += 1
fig = px.line(dfTmp, title="Validation F1 Scores", markers=True, width=1200)
for i in range(len(classList)):
    if i >= len(dashStyles):
        j = 1
    else:
        j = i
    fig.update_traces(selector={"name": classList[i]}, line={"dash": dashStyles[j]})
# fig.update_traces(stackgroup=None, fill='tonext')
fig.update_layout(xaxis=dict(title="Epochs"), yaxis=dict(title="F1 Score"), legend_title_text="Class Type")
fig.show()

In [ ]:
fig = px.bar(pd.DataFrame(history['f1_score'], columns=train_data_iterator.class_indices).mean(), title="Training F1 Average", text_auto=True, width=1200)
fig.update_layout(xaxis=dict(title="Class"), yaxis=dict(title="f1 score"), showlegend=False, yaxis_range=[0,1])

In [ ]:
pd.DataFrame(tsst, columns=train_data_iterator.class_indices).mean()

00. selfies             1.516
10. fmemes              1.444
20. ememes              1.120
30. eSocialMedia        1.000
40. fFbPosts            1.014
50. fTwtrPosts          1.000
60. fTxtMssgs           1.186
70. eGreetingAndMisc    1.078
dtype: float32

In [ ]:
fig = px.bar(pd.DataFrame(tsst, columns=train_data_iterator.class_indices).mean(), title="Validation F1 Average", text_auto=True, width=1200)
fig.update_layout(xaxis=dict(title="Class"), yaxis=dict(title="f1 score"), showlegend=False, yaxis_range=[0,1])

In [ ]:
history['test_f1_score'].reshape((1,8)).mean(axis=0)

array([0.9396 , 0.99292, 0.74301, 0.94952, 0.53801, 0.46377, 0.89134,
       0.77313])

In [ ]:
tf1 = history['test_f1_score'].copy()
tf1.reshape((1,8))
pd.DataFrame(history['test_f1_score'].reshape((1,-1)), columns=train_data_iterator.class_indices).squeeze().rename('Class') # squeezes the 1 row df to series

00. selfies             0.93960
10. fmemes              0.99292
20. ememes              0.74301
30. eSocialMedia        0.94952
40. fFbPosts            0.53801
50. fTwtrPosts          0.46377
60. fTxtMssgs           0.89134
70. eGreetingAndMisc    0.77313
Name: Class, dtype: float64

In [ ]:
pd.DataFrame({'class' : list(train_data_iterator.class_indices.keys()), 'value' : history['test_f1_score']}, index=train_data_iterator.class_indices)

class    value
00. selfies                    00. selfies  0.93960
10. fmemes                      10. fmemes  0.99292
20. ememes                      20. ememes  0.74301
30. eSocialMedia          30. eSocialMedia  0.94952
40. fFbPosts                  40. fFbPosts  0.53801
50. fTwtrPosts              50. fTwtrPosts  0.46377
60. fTxtMssgs                60. fTxtMssgs  0.89134
70. eGreetingAndMisc  70. eGreetingAndMisc  0.77313

In [ ]:
pd.DataFrame(tsst, columns=train_data_iterator.class_indices).mean().values

array([1.516    , 1.444    , 1.12     , 1.       , 1.014    , 1.       ,
       1.1860001, 1.078    ], dtype=float32)

In [ ]:
vals = pd.DataFrame(tsst, columns=train_data_iterator.class_indices).mean().values

In [ ]:
vals = pd.DataFrame(tsst, columns=train_data_iterator.class_indices).mean().values
fig = px.bar(pd.DataFrame({'class' : list(train_data_iterator.class_indices.keys()), 'value' : vals}, index=train_data_iterator.class_indices), 
        color='class', title="Testing F1 Average", text_auto=False, width=1200)
fig.update_layout(xaxis=dict(title="Class"), yaxis=dict(title="F1 score"), showlegend=True, yaxis_range=[0,1])

In [ ]:
fig = px.bar(pd.DataFrame({'class' : list(train_data_iterator.class_indices.keys()), 'value' : tsst}, index=train_data_iterator.class_indices), 
        color='class', title="Testing F1 Average", text_auto=False, width=1200)
fig.update_layout(xaxis=dict(title="Class"), yaxis=dict(title="F1 score"), showlegend=True, yaxis_range=[0,1])

In [ ]:
fig = px.bar(pd.DataFrame({'class' : list(train_data_iterator.class_indices.keys()), 'value' : history['test_f1_score']}, index=train_data_iterator.class_indices), 
        color='class', title="Testing F1 Average", text_auto=False, width=1200)
fig.update_layout(xaxis=dict(title="Class"), yaxis=dict(title="F1 score"), showlegend=True, yaxis_range=[0,1])

In [ ]:
fig = px.bar(pd.DataFrame(history['test_f1_score'].reshape((1,-1)), columns=train_data_iterator.class_indices).squeeze().rename('Class'), title="Testing F1 Average", text_auto=True, width=1200) # squeeze() the 1 row df to series
fig.update_layout(xaxis=dict(title="Class"), yaxis=dict(title="F1 score"), showlegend=False, yaxis_range=[0,1])

In [ ]:
plotTypeSingleModel(history, oneEpoch=True, average=False)['test_f1_score']